[package]
name = "deficiente_telegram_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "deficiente_telegram_bot"

[dependencies]
chrono = "0.4.38"
rand = "0.10.0"
regex = "1.10.4"
reqwest = { version = "0.13.0", features = ["json"] }
rust-embed = "8.5.0"
teloxide = { version = "0.17.0", features = ["macros", "webhooks-axum"] }
tokio = { version = "1.37", default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "time",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.0"

[profile.release]
lto = true        # Already enabled
codegen-units = 1 # Optimize for size at the cost of compile time
opt-level = 3     # Maximum optimizations
panic = "abort"   # Remove panic unwinding code
strip = true      # Remove debug symbols
