version: "3"
services:
  bot:
    image: adrianvillanueva997/telegrambot_deficiente
    container_name: telegram_deficiente
    restart: unless-stopped
    ports:
      - 2112
    env_file:
      - .env
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - bots
networks:
  bots:
    external: true
