version: '3'
services:
  bot:
    image: telegram_deficiente_bot
    container_name: telegram_deficiente_bot
    restart: unless-stopped
    networks:
      - bots
networks:
  bots:
    external: true