name: telegrambot_deficiente
services:
  bot:
    image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v8.7.0
    networks:
      - proxy
      - telegrambot_deficiente_network
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    labels:
      # Enable Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # HTTP to HTTPS redirect
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"

      # HTTP Router
      - "traefik.http.routers.deficiente-http.rule=Host(`deficiente.thexiao77.com`)"
      - "traefik.http.routers.deficiente-http.entrypoints=http"
      - "traefik.http.routers.deficiente-http.middlewares=redirect-https"

      # HTTPS Router
      - "traefik.http.routers.deficiente-https.rule=Host(`deficiente.thexiao77.com`)"
      - "traefik.http.routers.deficiente-https.entrypoints=https"
      - "traefik.http.routers.deficiente-https.tls=true"
      - "traefik.http.routers.deficiente-https.tls.certresolver=letsencrypt"

      - "traefik.http.services.deficiente.loadbalancer.server.port=8080"

    depends_on:
      - redis
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - URL=${URL}
      - REDIS_URL=${REDIS_URL}
      - ENVIRONMENT=prod

  redis:
    image: redis:7.4.2@sha256:6aafb7f25fc93c4ff74e99cff8e85899f03901bc96e61ba12cd3c39e95503c73
    container_name: telegrambot_deficiente_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - /mnt/telegrambot_deficiente_redis:/data
    labels:
      - "traefik.enable=false"
    networks:
      - telegrambot_deficiente_network
networks:
  proxy:
    external: true
  telegrambot_deficiente_network:
    driver: bridge
