name: telegrambot_deficiente
services:
  bot:
    image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v8.8.0
    networks:
      - proxy
      - telegrambot_deficiente_network
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    labels:
      # Enable Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # HTTP to HTTPS redirect
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"

      # HTTP Router
      - "traefik.http.routers.deficiente-http.rule=Host(`deficiente.thexiao77.com`)"
      - "traefik.http.routers.deficiente-http.entrypoints=http"
      - "traefik.http.routers.deficiente-http.middlewares=redirect-https"

      # HTTPS Router
      - "traefik.http.routers.deficiente-https.rule=Host(`deficiente.thexiao77.com`)"
      - "traefik.http.routers.deficiente-https.entrypoints=https"
      - "traefik.http.routers.deficiente-https.tls=true"
      - "traefik.http.routers.deficiente-https.tls.certresolver=letsencrypt"

      - "traefik.http.services.deficiente.loadbalancer.server.port=8080"

    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - URL=${URL}
      - ENVIRONMENT=prod
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

networks:
  proxy:
    external: true
  telegrambot_deficiente_network:
    driver: bridge
