version: '3'
services:
  bot:
    image: adrianvillanueva997/telegrambot_deficiente
    container_name: telegrambot_deficiente
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - TZ=Europe/Madrid
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - bots
networks:
  bots:
    external: true
