name: telegrambot_deficiente
services:
  web:
    image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v8.5.0@sha256:429e2d34c2b6ab41c3783eedf8b8e93e13d041b9e940eda8ba2e823ef5dcd64e
    networks:
      - telegrambot_deficiente
      - proxy
    container_name: telegrambot_deficiente
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - com.ouroboros.enable=true
      - "traefik.enable=true"
      - "traefik.http.middlewares.deficiente-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.deficiente-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.deficiente-web.middlewares=deficiente-redirect-websecure"
      - traefik.http.routers.deficiente-web.rule=Host(`deficiente.thexiao77.com`)
      - traefik.http.routers.deficiente-web.entrypoints=http
      - traefik.http.routers.deficiente-websecure.rule=Host(`deficiente.thexiao77.com`)
      - traefik.http.routers.deficiente-websecure.tls.certresolver=le
      - traefik.http.routers.deficiente-websecure.tls=true
      - traefik.http.routers.deficiente-websecure.entrypoints=https
      - "traefik.docker.network=proxy"
    depends_on:
      - redis
    env_file: stack.env

  redis:
    image: redis:7.2.4@sha256:66b2c641a6e16eeb188b64816f915a6313f15850d5dbea7c29736f59f9e5146c
    container_name: deficiente-redis
    restart: unless-stopped
    networks:
      - telegrambot_deficiente
    volumes:
      - /mnt/telegrambot_deficiente_redis:/data
    labels:
      - com.ouroboros.enable=true
      - "traefik.enable=false"
networks:
  proxy:
    external: true
  telegrambot_deficiente:
    external: false
    driver: bridge
