name: telegrambot_deficiente
services:
  bot:
    image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v8.7.0
    networks:
      - dokploy-network
      - telegrambot_deficiente_network
    container_name: telegrambot_deficiente
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegrambot_deficiente.rule=Host(`deficiente.thexiao77.com`)"
      - "traefik.http.routers.telegrambot_deficiente.entrypoints=websecure"
      - "traefik.http.routers.telegrambot_deficiente.tls.certResolver=letsencrypt"
      - "traefik.http.services.telegrambot_deficiente.loadbalancer.server.port=3000"

    depends_on:
      - redis
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - URL=${URL}
      - REDIS_URL=${REDIS_URL}
      - ENVIRONMENT=prod

  redis:
    image: redis:7.4.2@sha256:ca65ea36ae16e709b0f1c7534bc7e5b5ac2e5bb3c97236e4fec00e3625eb678d
    container_name: telegrambot_deficiente_redis
    restart: unless-stopped
    volumes:
      - /mnt/telegrambot_deficiente_redis:/data
    labels:
      - "traefik.enable=false"
    networks:
      - telegrambot_deficiente_network
networks:
  dokploy-network:
    external: true
  telegrambot_deficiente_network:
    driver: bridge
