name: telegrambot_deficiente
services:
  bot:
    image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v8.6.3
    networks:
      - proxy
      - telegrambot_deficiente_network
    container_name: telegrambot_deficiente
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - com.ouroboros.enable=true
      - "traefik.enable=true"
      - "traefik.http.middlewares.deficiente-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.deficiente-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.deficiente-web.middlewares=deficiente-redirect-websecure"
      - traefik.http.routers.deficiente-web.rule=Host(`deficiente.thexiao77.com`)
      - traefik.http.routers.deficiente-web.entrypoints=http
      - traefik.http.routers.deficiente-websecure.rule=Host(`deficiente.thexiao77.com`)
      - traefik.http.routers.deficiente-websecure.tls.certresolver=le
      - traefik.http.routers.deficiente-websecure.tls=true
      - traefik.http.routers.deficiente-websecure.entrypoints=https
      - "traefik.docker.network=proxy"
    depends_on:
      - redis
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - URL=${URL}
      - REDIS_URL=${REDIS_URL}

  redis:
    image: redis:7.4.0@sha256:79676a8f74e4aed85b6d6a2f4e4e3e55d8a229baa7168362e592bbfdc67b0c9b
    container_name: telegrambot_deficiente_redis
    restart: unless-stopped
    volumes:
      - /mnt/telegrambot_deficiente_redis:/data
    labels:
      - com.ouroboros.enable=true
      - "traefik.enable=false"
    networks:
      - telegrambot_deficiente_network
networks:
  proxy:
    external: true
  telegrambot_deficiente_network:
    driver: bridge
