name: telegrambot_deficiente
services:
  bot:
    image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v8.7.0
    networks:
      - coolify
      - telegrambot_deficiente_network
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.telegrambot_deficiente-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.telegrambot_deficiente-redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.telegrambot_deficiente-http.middlewares=telegrambot_deficiente-redirect-https
      - traefik.http.routers.telegrambot_deficiente-http.rule=Host(`deficiente.thexiao77.com`)
      - traefik.http.routers.telegrambot_deficiente-http.entrypoints=http
      - traefik.http.routers.telegrambot_deficiente-https.rule=Host(`deficiente.thexiao77.com`)
      - traefik.http.routers.telegrambot_deficiente-https.tls.certresolver=letsencrypt
      - traefik.http.routers.telegrambot_deficiente-https.tls=true
      - traefik.http.routers.telegrambot_deficiente-https.entrypoints=https
      - traefik.docker.network=coolify

    depends_on:
      - redis
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - URL=${URL}
      - REDIS_URL=${REDIS_URL}
      - ENVIRONMENT=prod

  redis:
    image: redis:7.4.2@sha256:ca65ea36ae16e709b0f1c7534bc7e5b5ac2e5bb3c97236e4fec00e3625eb678d
    container_name: telegrambot_deficiente_redis
    restart: unless-stopped
    volumes:
      - /mnt/telegrambot_deficiente_redis:/data
    labels:
      - "traefik.enable=false"
    networks:
      - telegrambot_deficiente_network
networks:
  coolify:
    external: true
  telegrambot_deficiente_network:
    driver: bridge
