version: "3.0"
services:
  redis:
    image: redis:alpine@sha256:de13e74e14b98eb96bdf886791ae47686c3c5d29f9d5f85ea55206843e3fce26
    container_name: deficiente-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
networks:
  proxy:
    external: true
