version: "3.0"
services:
  redis:
    image: redis:alpine@sha256:28c9c4d7596949a24b183eaaab6455f8e5d55ecbf72d02ff5e2c17fe72671d31
    container_name: deficiente-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
networks:
  proxy:
    external: true
