version: "3.0"
services:
  redis:
    image: redis:alpine@sha256:0779069b3c24a47a2f681855c1c01d046793e7c5f7d2b079c2aa0652c42eaf0e
    container_name: deficiente-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
networks:
  proxy:
    external: true
