apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegrambot-deficiente-redis-pvc
  namespace: telegrambot-deficiente
spec:
  storageClassName: telegrambot-deficiente-redis-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: telegrambot-deficiente-redis-local-storage
  namespace: telegrambot-deficiente
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegrambot-deficiente-redis-pv
  namespace: telegrambot-deficiente
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: telegrambot-deficiente-redis-local-storage
  local:
    path: /mnt/telegrambot-deficiente-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vmi1572623.contaboserver.net
