apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: telegrambot-deficiente-letsencrypt-staging
  namespace: telegrambot-deficiente
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: telegrambot-deficiente-staging
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: telegrambot-deficiente-letsencrypt-production
  namespace: telegrambot-deficiente
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: telegrambot-deficiente-production
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik
