name: Hadolint

on:
  pull_request:
    branches:
      - main

jobs:
  Hadolint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine@sha256:d02f8512ac8bf166cc93a43cfa56c22cdb1afe7ef173dc390878348e4a269bb8
    strategy:
      matrix:
        architectures:
          - linux/amd64
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install Just
        run: apk add --no-cache just
      - name: Run Hadolint
        run: just hadolint
