name: Hadolint

on:
  pull_request:
    branches:
      - main

jobs:
  Hadolint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine@sha256:e6f3fb90751bd85e53e4f0b758fbd77bce25833c80d9dcdb49aabc5ee39ff018
    strategy:
      matrix:
        architectures:
          - linux/amd64
    steps:
      - name: Check out code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Install Just
        run: apk add --no-cache just
      - name: Run Hadolint
        run: just hadolint
