name: Hadolint

on:
  pull_request:
    branches:
      - main

jobs:
  run-clippy:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine
    strategy:
      matrix:
        architectures:
          - linux/amd64
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Just
        run: apk add --no-cache just
      - name: Run Hadolint
        run: just hadolint
