name: Hadolint

on:
  pull_request:
    branches:
      - main

jobs:
  Hadolint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine@sha256:be27962427a85de242820cb710a374478cce9bfb534a2c07e4fa54741d98908f
    strategy:
      matrix:
        architectures:
          - linux/amd64
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Just
        run: apk add --no-cache just
      - name: Run Hadolint
        run: just hadolint
