name: Build Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:alpine
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk add --no-cache make
          make fmt
  gosec:
    runs-on: ubuntu-latest
    container: securego/gosec:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk add --no-cache make
          make sec
  golangci-lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk add --no-cache make
          make golancilint
  docker-lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk add --no-cache make
          make docker-lint2
  build-docker:
    runs-on: ubuntu-latest
    needs: [security-check, lint, gosec, golangci-lint, docker-lint]
    steps:
      - name: Set up CD
        uses: actions/checkout@v3
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v2.0.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Docker login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/adrianvillanueva997/deficientebot_telegram:latest
          labels: ${{ steps.meta.outputs.labels }}

          #tags: |
          #  adrianvillanueva997/telegrambot_deficiente:${{ github.sha }}
          #  adrianvillanueva997/telegrambot_deficiente:latest
