name: Build Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk add --no-cache make
          make docker-lint
  build-docker:
    runs-on: ubuntu-latest
    needs: [docker-lint]
    steps:
      - name: Set up CD
        uses: actions/checkout@v3
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v2.1.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/adrianvillanueva997/deficientebot_telegram:latest
          labels: ${{ steps.meta.outputs.labels }}

          #tags: |
          #  adrianvillanueva997/telegrambot_deficiente:${{ github.sha }}
          #  adrianvillanueva997/telegrambot_deficiente:latest
