name: Build Docker image

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, closed ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: [ 'go' ]
        # Learn more...
    container:
      image: golang
    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
          go mod download
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t bot .